kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: bg3-tools-production-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
  volumeMode: Filesystem