---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{ .Values.appName }}-master-key
  namespace: apps-production
spec:
  encryptedData:
    RAILS_MASTER_KEY: {{ .Values.sealed_secrets.RAILS_MASTER_KEY }}
  template:
    metadata:
      creationTimestamp: null
      name: {{ .Values.appName }}-master-key
      namespace: apps-production
