# Solid Cable adapter works across processes, so you can trigger cable updates from console,
# and see results in the browser. Add "console" to any action or any ERB template view
# to make the web console appear.
development:
  adapter: solid_cable
  connects_to:
    database:
      writing: development
  polling_interval: 0.1.seconds
  message_retention: 1.day

test:
  adapter: test

production:
  adapter: solid_cable
  connects_to:
    database:
      writing: cable
  polling_interval: 0.1.seconds
  message_retention: 1.day
